version: "3"
services:
  web:
    image: sample-project-with-docker
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - nginx
      - db
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=pavel
      - POSTGRES_USER=ps
      - POSTGRES_DB=ps
    ports:
      - 5433:5432